publishDir = "docs"


baseurl = "https://phongtlam.github.io/myjourney/"
title = "Phong Lam"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "My portfolio/blog"
  copyright = "&copy;2017 Phong Lam"
  sidebarAbout = [
    "Phong specializes in making beautiful software and user interfaces. He has a passion for all things science and chess AI. When not coding, heâ€™d be reading, writing, listening to music or working out at the gym. Follow his journey as a developer or just send him a message to connect."
  ]

  email = "phongtlam@gmail.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Blog"
  url = "blog/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  email         = "phongtlam@gmail.com"
  linkedin      = "https://www.linkedin.com/in/phongtlam/"
  angellist     = "https://angel.co/phongtlam"
  github        = "https://github.com/Phongtlam"
  soundcloud    = "https://soundcloud.com/phong-twitch-lam"
